{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
  labels:
    app.kubernetes.io/name: quakewatch
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: "Helm"
type: Opaque
stringData:
  SECRET_TOKEN: {{ .Values.secret.token | quote }}
{{- end }}
