apiVersion: v1
kind: Service
metadata:
  name: {{ include "quakewatch.fullname" . }}
  labels:
    {{- include "quakewatch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "quakewatch.selectorLabels" . | nindent 4 }}
