fullnameOverride: "quakewatch-helm"

image:
  repository: vitalybelos112/quakewatch
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

containerPort: 5000

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  replicaCount: 2
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

env:
  appMessage: "Hello from ConfigMap"

secret:
  useExisting: true
  existingName: quakewatch-secret

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []