replicaCount: 2

image:
  repository: vitalybelos112/quakewatch
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

config:
  appMessage: "Hello, World!"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
