apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-ping
  labels:
    app: quakewatch-ping
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        metadata:
          labels:
            app: quakewatch-ping
            job: quakewatch-ping
        spec:
          restartPolicy: OnFailure
          containers:
            - name: curl
              image: curlimages/curl:8.10.1
              resources:
                requests:
                  cpu: 10m      
              args: ["-sS","-m","5","http://quakewatch","-o","/dev/null","-w","HTTP %{http_code}\n"]
